### ISSUE TITLE
Does not work in 2022

### ISSUE THREAD

**Issue by barser** [kolsys/TorrServer.bundle#2]

**Comment by kolsys** [comment]
TorreServer has native DLNA support. I don't see any reason to support project since Plex discontinued official plugin support.

**Comment by mihalt** [comment]
> TorreServer has native DLNA support. I don't see any reason to support project since Plex discontinued official plugin support.

But Plex doesn't support DLNA from the box too https://forums.plex.tv/t/how-to-use-plex-as-dlna-client/870871
